species: ecoli
data_dir: data #name and path of the data directory
output_dir: output #name and path of the output directory
zipped_ref_genome_filepath: data/ncbi_dataset.zip #zipped reference genome file for ecoli
zipped_gtf_filepath: data/ncbi_dataset.zip  #zipped gtf file for ecoli
input_type: fastq #'sra' for NCBI SRA downloads, 'fastq' for custom FASTQ files
sra_run: 
  filepath: SraRunTable.txt #sra run list for ecoli (not used when input_type is 'fastq')
  number_of_runs: 4 #number of runs to analyse (not used when input_type is 'fastq')
fastq_input:
  sample_list: custom_samples.txt #file listing sample names (one per line)
  fastq_dir: data/ecoli/fastq #directory containing FASTQ files (expects {sample}_R1.fastq.gz and {sample}_R2.fastq.gz format)
threads: 10
low: 0 #lower bp range
high: 10000 #upper bp range
gene: y #(y/n) -- includes gene annotations if 'y'