species: #species name
data_dir: #name and path of the data directory
output_dir: #name and path of the output directory
zipped_ref_genome_filepath: #zipped reference genome file for species
zipped_gtf_filepath:  #zipped gtf file for species
input_type: #'sra' for NCBI SRA downloads, 'fastq' for custom FASTQ files
sra_run: 
  filepath: #sra run list for species
  number_of_runs: #number of runs to analyse
fastq_input:
  sample_list: #file listing sample names (one per line)
  fastq_dir: #directory containing FASTQ files (expects {sample}_R1.fastq.gz and {sample}_R2.fastq.gz format)
threads: #number of threads for downloading bam files
low: #lower bp range
high: #upper bp range
gene: #(y/n) -- includes gene annotations if 'y'
