species: eFus
data_dir: data
output_dir: output
zipped_ref_genome_filepath: data/mEptFus1.3.pri.fa.zip
zipped_gtf_filepath: data/eFus_toga.gtf.zip
fastq_input:
  sample_list: eFus_samples.txt
  fastq_dir: data/horse/fastq
input_type: fastq
threads: 4
low: 0
high: 10000
gene: y
